global using NUnit.Framework;
global using Regula.FaceSDK.WebClient.Model;
global using System.Collections.Generic;
global using System.IO;
global using Regula.FaceSDK.WebClient.Api;
global using System;
global using System.Reflection;
global using Regula.FaceSDK.WebClient.Client;
global using System.Diagnostics;